flaskpage/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

class MessageForm(FlaskForm):
	name = StringField('Vārds Uzvārds', validators=[DataRequired()])
	title = StringField('Temats', validators=[DataRequired()])
	content = TextAreaField('Ziņojums', validators=[DataRequired()])
	submit = SubmitField('Send')

	def validate_email(self, name):
		if false:
			raise ValidationError('No account found with that email.')

flaskpage/__init__.py
from flask import Flask
#from flask_sqlalchemy import SQLAlchemy
#from flask_bcrypt import Bcrypt
#from flask_login import LoginManager
from flask_mail import Mail
from flaskpage.config import Config

#db = SQLAlchemy()
#bcrypt = Bcrypt()
#login_manager = LoginManager()
#login_manager.login_view = 'users.login'
#login_manager.login_message_category = 'info'
mail = Mail()


def create_app(Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    #db.init_app(app)
    #bcrypt.init_app(app)
    #login_manager.init_app(app)
    mail.init_app(app)

    from flaskpage.routes import mainBP, errorsBP
    app.register_blueprint(mainBP)
    app.register_blueprint(errorsBP)

    return app

flaskpage/routes.py
from flask import render_template, url_for, flash, abort, redirect, request, Blueprint
from flaskpage.utils import send_message
from flaskpage.forms import (MessageForm)

mainBP = Blueprint('main', __name__)
errorsBP = Blueprint('errors', __name__)

@mainBP.route("/")
@mainBP.route("/about")
def about():
	return render_template('about.html', title='Par')

@mainBP.route("/")
@mainBP.route("/contact", methods=['GET', 'POST'])
def contact():
	form = MessageForm()
	if form.validate_on_submit():
		send_message(form.name.data, form.title.data, form.content.data)
		flash('Ziņojums nosūtīts!', 'success')
		return redirect(url_for('main.contact'))
	elif request.method == 'GET':
		return render_template('contact.html', title='Kontakti', form=form)

@errorsBP.app_errorhandler(404)
def error_404(error):
	return render_template('errors/404.html'), 404

@errorsBP.app_errorhandler(403)
def error_403(error):
	return render_template('errors/403.html'), 403

@errorsBP.app_errorhandler(500)
def error_500(error):
	return render_template('errors/500.html'), 500

flaskpage/templates/about.html
{% extends "base.html" %}
{% block content %}
<div class="content-section p-3">
	<legend class="border-bottom mb-4">I.Kuzmas ĢĀP</legend>
	<p>Ilzes Kuzmas ģimenes ārsta prakse sniedz medicīniskās palīdzības ambulatorā pakalpojumus, tā tika dibināta 199X gadā. Sobrīd apgādā ap 1700 pacentus no visām vecumu grupām.</p>
	<legend class="border-bottom mb-4">Addrese</legend>
	<p>Alejas iela 8, Kocēni, Kocēnu pagasts, Kocēnu novads, Latvia, LV-4220, Tel. Nr. 64229093</p>
	<img class="w-100" src="https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fwww.valmieraszinas.lv%2Fwp-content%2Fuploads%2F2020%2F05%2Fkocenu-domes-eka-renovacija-autors-pasvaldiba.jpg&sp=1593125214T9107725036c6b0745ae95b92e3e01fdd7ad1487d31a69a8f81787ce078141ac0">
</div>
{% endblock content %}

flaskpage/templates/base.html
<!DOCTYPE html>
<html>
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

		{% if title == 'Par' %}
			<title>{{ title }} I.Kuzmas ĢĀP</title>
		{% else %}
			<title>I.Kuzmas ĢĀP {{ title }}</title>
		{% endif %}
</head>
<body>
	<nav class="navbar-dark fixed-top" style="background-color:#0088FF">
	 	<div role="main" class="navbar-expand container pb-2 pt-2">
			<div class="row pl-3 pr-3">
				<div class="row container m-0 p-0">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item pl-2">
							<a class="nav-link {% if title=='Par' %} active {% endif %} mr-auto" href="{{ url_for('main.about') }}">Par Mums</a>
						</li>
						<li class="nav-item pl-2">
							<a class="nav-link {% if title=='Kontakti' %} active {% endif %}" href="{{ url_for('main.contact') }}">Kontakti</a>
						</li>
					</ul>
				</div>
			</div>
	 	</div>
	</nav>
	<main class="container">
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category, message in messages %}
				<div class="alert alert-{{ category }}">
					{{ message }}
				</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
		{% block content %}{% endblock %}
	</main>


		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskpage/templates/contact.html
{% extends "base.html" %}
{% block content %}
<article class="content-section p-3 d-flex">
	<img class="rounded-circle article-img" style="width:100px; height:100px; object-fit:cover; object-position:top" src="https://scontent.frix7-1.fna.fbcdn.net/v/t31.0-1/p160x160/13584891_103725086731208_108092937553999276_o.jpg?_nc_cat=100&_nc_sid=dbb9e7&_nc_oc=AQnn3q0BWfWiwqDCdLcFNpuStXXIR4zycN8bB3NfkhOsE7JuKnyNbMn6E7vatct2x8o&_nc_ht=scontent.frix7-1.fna&_nc_tp=6&oh=7709459cefcfe74f65e5d20619c4dc31&oe=5F1BE36A">
	<div class="w-100">
		<legend class="border-bottom mb-1">Ilze Kuzma</legend>
		<p class="mb-1">Profesija: Ārsts</p>
		<p class="mb-1">Mob. Tel. 29143091</p>
		<p class="mb-1">E-pasts: ilze.kuzma@gmail.com</p>
	</div>
</article>
<article class="content-section p-3 d-flex">
	<img class="rounded-circle article-img" style="width:100px; height:100px; object-fit:cover; object-position:top" src="http://www.koceni.lv/_/rsrc/1548764499305/dome/priekssedetajs-deputati/Sarmi%CC%84te_Brac%CC%8Cka.jpg?height=400&width=266">
	<div class="w-100">
		<legend class="border-bottom mb-1">Sarmīte Bračka</legend>
		<p class="mb-1">Profesija: Ārsta palīgs</p>
		<p class="mb-1">Mob. Tel. 29466623</p>
		<p class="mb-1">E-pasts: sarmite.bracka@kocenunovads.lv</p>
	</div>
</article>
<article class="content-section p-3 d-flex">
	<img class="rounded-circle article-img" style="width:100px; height:100px; object-fit:cover; object-position:top" src="https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fdailytimes.com.pk%2Fassets%2Fuploads%2F2018%2F07%2F08%2FNo-pics.jpg&sp=1593125052Tbabc1ccc9ee1f0f860840afc2a3d4809a916cbbbdd8e63fd6e135021a93f4ed9">
	<div class="w-100">
		<legend class="border-bottom mb-1">Ināra Malceniece</legend>
		<p class="mb-1">Profesija: Ārsta palīgs</p>
		<p class="mb-1">Mob. Tel. 29296591</p>
	</div>
</article>
<div class="content-section">
	<form class="container" method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group mb-1 row">
			<legend class="border-bottom mb-4">Sazināties caur E-pastu</legend>

			<div class="row">
				<div class="form-group col-sm-6 col-lg-5 col-xl-4">
					{{ form.name.label(class="form-control-label mb-1") }}
					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg is-invalid p-1") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg p-1") }}
					{% endif %}
				</div>
				<div class="form-group col-sm-6 col-lg-5 col-xl-4">
					{{ form.title.label(class="form-control-label mb-1") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid p-1") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg p-1") }}
					{% endif %}
				</div>
				<div class="form-group col-sm-12 col-lg-10 col-xl-8">
					{{ form.content.label(class="form-control-label mb-1") }}
					{% if form.content.errors %}
						{{ form.content(class="form-control form-control-lg is-invalid p-1") }}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class="form-control form-control-lg p-1", rows="4") }}
					{% endif %}
				</div>
			</div>
			
		</fieldset>
		<div class="form-group row">
				{{ form.submit(class="btn btn-outline-info", value="Nosūtīt") }}
		</div>
	</form>
</div>
{% endblock content %}